; Load everything (for interactive use: ULisp)

(load "ulisp-specific.scm")
(load "../lib/term.scm")
(load "../lib/kanren.ss")
;(load "../examples/type-inference.scm")
;(load "../examples/typeclasses.scm")
(load "../examples/zebra.scm")
(load "../examples/mirror.scm")
(load "../examples/mirror-equ.scm")
(load "../examples/deduction.scm")
(load "../examples/pure-bin-arithm.scm")
(load "../benchmarks/nrev.scm")
(load "../benchmarks/queens.scm")
