#! /bin/sh

if [ ! -f "wordlist.txt" ]; then
  if [ -f "/usr/share/dict/words" ]; then
    echo "Wordlist missing -- symlinking the system dictionary."
    ln -s /usr/share/dict/words wordlist.txt
  fi
fi

../../../retro --image ../../../retroImage --with hangman.retro
